from guizero import App, Text, Box
app = App(title = "guizero", width = 400, height = 400)
box_main = Box(app, layout = "grid", height = 300, width = 300)
box_text = Box(box_main, width = 300, height = 100, grid = [0,0,2,1], border = True)
text = Text(box_text, text = "Điểm môn học", size = 20, color = "red")
box_subject = Box(box_main, width = 150, height = 100, grid = [0,1], border = True)
subject_1 = Text(box_subject, text = "Toán", size = 15, color = "black")
subject_2 = Text(box_subject, text = "Ngữ văn", size = 15, color = "black")
subject_3 = Text(box_subject, text = "Tiếng Anh", size = 15, color = "black")
box_score = Box(box_main, width = 150, height = 100, grid = [1,1], border = True)
score_1 = Text(box_score, text = "8", size = 15, color = "black")
score_2 = Text(box_score, text = "9", size = 15, color = "black")
score_3 = Text(box_score, text = "10", size = 15, color = "black")
box_tbc = Box(box_main, width = 300, height = 100, grid = [0,2,2,1], border = True)
text_tbc = Text(box_tbc, text = "Điểm trung bình:", size = 20, color = "red")
tbc = Text(box_tbc, text = str((8 + 9 + 10) / 3), size = 20, color = "red")
app.display()